DESIGN_NAME: S4NoC
VERILOG_FILES:
  - dir::../../generated/PicoMeshBigTop.v

VDD_NETS: ["vccd1"]
GND_NETS: ["vssd1"]

CLOCK_PORT: clock
CLOCK_PERIOD: 20

TIMING_VIOLATION_CORNERS: []

FP_PDN_MULTILAYER: true
FP_PDN_CORE_RING: true


# DESIGN_REPAIR_MAX_SLEW_PCT: 12
# DESIGN_REPAIR_MAX_CAP_PCT: 12
# GRT_DESIGN_REPAIR_MAX_SLEW_PCT: 12
# GRT_DESIGN_REPAIR_MAX_CAP_PCT: 12
# RUN_ANTENNA_REPAIR: true
# GRT_ANTENNA_ITERS: 10

#GRT_ALLOW_CONGESTION: true

#PL_TARGET_DENSITY_PCT: 66
FP_CORE_UTIL: 40
FP_ASPECT_RATIO: 0.6
#FP_PIN_ORDER_CFG: dir::pin_order.cfg
#FP_SIZING: absolute
#DIE_AREA: [0, 0, 665, 265]
SYNTH_AUTONAME: true
#FP_DEF_TEMPLATE: template.def
# FP_OBSTRUCTIONS:
#   - [330, 330, 550, 550]
# ROUTING_OBSTRUCTIONS:
#   - "met1 330 330 550 550"
#   - "met2 330 330 550 550"
#   - "met3 330 330 550 550"
#   - "met4 330 330 550 550"
#   - "met5 330 330 550 550"
# PDN_OBSTRUCTIONS:
#   - "met4 330 330 550 550"
#   - "met5 330 330 550 550"
# SYNTH_AUTONAME: true
# SYNTH_HIERARCHY_MODE: keep
#SYNTH_SIZING: true
#SYNTH_STRATEGY: "DELAY 0"

# PL_WIRE_LENGTH_COEF: 0.10
# DESIGN_REPAIR_MAX_WIRE_LENGTH: 300
# GRT_ANTENNA_MARGIN: 25
# GRT_ANTENNA_ITERS: 40