DESIGN_NAME: Battuta
VERILOG_FILES:
  - dir::../../generated/Battuta.v
  - dir::../../src/verilog/picorv32.v

VDD_NETS: ["vccd1"]
GND_NETS: ["vssd1"]

CLOCK_PORT: clock
CLOCK_PERIOD: 10

TIMING_VIOLATION_CORNERS: []

STA_CORNERS:
 - nom_tt_025C_1v80
 - min_tt_025C_1v80
 - max_tt_025C_1v80

FP_PDN_MULTILAYER: true
FP_PDN_CORE_RING: true
#RT_MAX_LAYER: met4
#GRT_ALLOW_CONGESTION: true

# DESIGN_REPAIR_MAX_SLEW_PCT: 12
# DESIGN_REPAIR_MAX_CAP_PCT: 12
# GRT_DESIGN_REPAIR_MAX_SLEW_PCT: 12
# GRT_DESIGN_REPAIR_MAX_CAP_PCT: 12
# RUN_ANTENNA_REPAIR: true
# GRT_ANTENNA_ITERS: 10

#GRT_ALLOW_CONGESTION: true

GRT_ANTENNA_REPAIR_DIODE_ONLY: true
PRIMARY_GDSII_STREAMOUT_TOOL: "klayout"
MAGIC_CAPTURE_ERRORS: false

FALLBACK_SDC: dir::base.sdc

PL_TARGET_DENSITY_PCT: 40
FP_CORE_UTIL: 40
#FP_ASPECT_RATIO: 1.5
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_SIZING: absolute
DIE_AREA: [0, 0, 2000, 2000]
SYNTH_AUTONAME: true
#FP_DEF_TEMPLATE: template.def
# FP_OBSTRUCTIONS:
#   - [330, 330, 550, 550]
# ROUTING_OBSTRUCTIONS:
#   - "met1 330 330 550 550"
#   - "met2 330 330 550 550"
#   - "met3 330 330 550 550"
#   - "met4 330 330 550 550"
#   - "met5 330 330 550 550"
# PDN_OBSTRUCTIONS:
#   - "met4 330 330 550 550"
#   - "met5 330 330 550 550"
# SYNTH_AUTONAME: true
# SYNTH_HIERARCHY_MODE: keep
#SYNTH_SIZING: true
#SYNTH_STRATEGY: "DELAY 0"

# PL_WIRE_LENGTH_COEF: 0.10
# DESIGN_REPAIR_MAX_WIRE_LENGTH: 300
# GRT_ANTENNA_MARGIN: 25
# GRT_ANTENNA_ITERS: 40

ERROR_ON_LVS_ERROR: false

MACROS:
  sky130_sram_1kbyte_1rw1r_32x256_8:
    instances:
      array.memLowTile.mem:
        location: [100, 100]
        orientation: FS
      array.memHighTile.mem:
        location: [700, 100]
        orientation: S
    gds: dir::../../../gds/sky130_sram_1kbyte_1rw1r_32x256_8.gds
    lef: pdk_dir::libs.ref/sky130_sram_macros/lef/sky130_sram_1kbyte_1rw1r_32x256_8.lef
    nl: pdk_dir::libs.ref/sky130_sram_macros/verilog/sky130_sram_1kbyte_1rw1r_32x256_8.v
PDN_MACRO_CONNECTIONS:
  - "array.memLowTile.mem vccd1 vssd1 vccd1 vssd1"
  - "array.memHighTile.mem vccd1 vssd1 vccd1 vssd1"
